flyway.url=jdbc:postgresql://ep-red-moon-am3d1oj2-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
flyway.user=${POSTGRES_USER}
flyway.password=${POSTGRES_PASSWORD}
flyway.locations=filesystem:/flyway/sql
flyway.driver=org.postgresql.Driver